[General]
; Whether the autobuy macro should also buy stacks of 100 items (1 to enable)
bAutobuyStacks=0
; Make a sound beep when suspending/unsuspending the script (1 to enable)
bBeepOnSuspend=1
; Whether Escape should act like Shift + Escape (1 to enable)
bForceShiftEscape=0
; Swap up and down while autoswimming (1 to enable)
bInvertControlsWhenAutoswimming=0
; When turning the Sneak key into a hold key, try to make the character stand back up when releasing the key before the crouching animation is over (1 to enable).
; There are lots of instances where your character can't sneak, so it may become desynced at some point.
bWaitForSneakAnimation=0
; How often should we send mouse click when autobuying (in milliseconds), lower values makes buying items faster
iAutobuyClickFrequency=100
; How often should we send Jump when autojumping (in milliseconds), 300-500 seems like a good value overall, below 200 doesn't give time for your character to move forward after landing
iAutojumpFrequency=300

; See https://www.autohotkey.com/docs/v2/KeyList.htm for key IDs
; Any key should only be used once or it'll lead to unwanted results
[MandatoryKeys]
; The hotkey used for action
sActionKey="f"
; The hotkey used to move backward
sBackwardKey="s"
; The hotkey used to move forward
sForwardKey="w"
; The hotkey used to jump
sJumpKey="Space"
; The hotkey used to display your character status
sPlayerStatusKey="z"
; The hotkey used to bring up the Steam overlay (make sure the Steam overlay isn't displayed beforehand)
sSteamOverlayKey="ScrollLock"

; You can make a key blank to disable it
[OptionalKeys]
; The hotkey used for fast attacking (make sure your weapon is drawn beforehand)
sFastAttackKey="MButton"
; The hotkey used for looting
sLootKey="XButton1"
; The hotkey used for loading quick saves
sQuickLoadKey="F9"
; Lets you remap right-click to another key (requires https://steamcommunity.com/sharedfiles/filedetails/?id=3210234170 to work)
sRightClickKey=""
; The hotkey used for smithing (hold it until you notice the smithing animation gets cancelled)
sSmithKey="XButton2"
; The hotkey used for sneaking (turns it into a hold key)
sSneakKey="LCtrl"
; The hotkey used to toggle autobuy
sToggleAutobuyKey="k"
; The hotkey used to toggle autocook (make sure you're looking at a pan and are within range beforehand)
sToggleAutocookKey="l"
; The hotkey used to toggle autojump (works best on flat ground and upward slopes)
sToggleAutojumpKey="F2"
; The hotkey used to toggle autorun (shouldn't be used underwater)
sToggleAutorunKey="F1"
; The hotkey used to toggle autoswim (should only be used underwater)
sToggleAutoswimKey="x"
; The hotkey used to toggle first-person mode (must be the same as the in-game "Look around first person" key)
sToggleFirstPersonModeKey="e"
; The hotkey used to toggle Marvin mode (to use cheats)
sToggleMarvinModeKey="F3"
; The hotkey used to toggle walk (must be the same as the in-game "Run" key)
sToggleWalkKey="LShift"