[General]
; Make a sound beep when suspending/unsuspending the script (1 to enable)
bBeepOnSuspend=1
; How often should we send mouse click when autobuying (in milliseconds), lower values makes buying different items faster
iAutobuyClickFrequency=100

; See https://www.autohotkey.com/docs/v2/KeyList.htm for key IDs
[MandatoryKeys]
; The hotkey used for action
sActionKey="f"
; The hotkey used to move backward
sBackwardKey="s"
; The hotkey used to move forward
sForwardKey="w"
; The hotkey used to jump
sJumpKey="Space"
; The hotkey used to bring up the Steam overlay
sSteamOverlayKey="ScrollLock"

[OptionalKeys]
; The hotkey used to fast attack (hold)
sFastAttackKey="MButton"
; The hotkey used to autobuy (toggle)
sToggleAutobuyKey="k"
; The hotkey used to autocook (toggle)
sToggleAutocookKey="l"
; The hotkey used to autojump (toggle)
sToggleAutojumpKey="F2"
; The hotkey used to autorun (toggle)
sToggleAutorunKey="F1"
; The hotkey used to walk (toggle), must be the same as the in-game walk key
sToggleWalkKey="Shift"
