[General]
; Make a sound beep when suspending/unsuspending the script (1 to enable)
bBeepOnSuspend=1
; How often should we send mouse click when autobuying (in milliseconds), lower values makes buying items faster
iAutobuyClickFrequency=100

; See https://www.autohotkey.com/docs/v2/KeyList.htm for key IDs
[MandatoryKeys]
; The hotkey used for action
sActionKey="f"
; The hotkey used to move backward
sBackwardKey="s"
; The hotkey used to move forward
sForwardKey="w"
; The hotkey used to jump
sJumpKey="Space"
; The hotkey used to bring up the Steam overlay
sSteamOverlayKey="ScrollLock"

; Make a key blank to disable it
[OptionalKeys]
; The hotkey used for fast attacking (hold)
sFastAttackKey="MButton"
; The hotkey used for loading quick saves
sQuickLoadKey="F9"
; Lets you remap right-click to another key (requires https://steamcommunity.com/sharedfiles/filedetails/?id=3210234170)
sRightClickKey=""
; The hotkey used for smithing (hold)
sSmithKey="XButton2"
; The hotkey used to toggle autobuy
sToggleAutobuyKey="k"
; The hotkey used to toggle autocook
sToggleAutocookKey="l"
; The hotkey used to toggle autojump
sToggleAutojumpKey="F2"
; The hotkey used to toggle autorun
sToggleAutorunKey="F1"
; The hotkey used to toggle autoswim
sToggleAutoswimKey="x"
; The hotkey used to toggle walk, must be the same as the in-game walk key
sToggleWalkKey="Shift"
